build-root=C:/path/to/build/root

forge-path=relative/path/to/Forge/build/libs
fabric-path=relative/path/to/Fabric/build/libs
neoforge-path=relative/path/to/NeoForge/build/libs

forge-file-format=modid-forge-%s-%s.jar
fabric-file-format=modid-fabric-%s-%s.jar
neoforge-file-format=modid-neoforge-%s-%s.jar

modrinth-auth-token=your-modrinth-auth-token-here
modrinth-project-id=your-modrinth-project-id-here

curse-forge-auth-token=your-curse-forge-auth-token-here
curse-forge-project-id=your-curse-forge-project-id-here

version-name=ModName some-version
version-number=1.0.0

publish-to-modrinth=false
publish-to-curse-forge=false
